---
- name: Debug Ansible SSh
  hosts: servers
  gather_facts: false

  tasks:
    - name: show ssh login
      become: false
      command: whoami
      register: ssh_user

    - name: Print SSh resutl
      debug:
        var: ssh_user.stdout
    - name: Test sudo
      become: true
      command: whoami
      register: sudo_user

    - name: Print sudo result
      debug:
        var: sudo_user.stdout
