---
- name: Install Nginx
  hosts: all
  become: true

  tasks:
    - name: Install Nginx package
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
        lock_timeout: 300
